/* bluecon.c generated by valac 0.14.0, the Vala compiler
 * generated from bluecon.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define TYPE_ADAPTER (adapter_get_type ())
#define ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ADAPTER, Adapter))
#define IS_ADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ADAPTER))
#define ADAPTER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_ADAPTER, AdapterIface))

typedef struct _Adapter Adapter;
typedef struct _AdapterIface AdapterIface;

#define TYPE_ADAPTER_PROXY (adapter_proxy_get_type ())
typedef GDBusProxy AdapterProxy;
typedef GDBusProxyClass AdapterProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))

#define TYPE_MANAGER (manager_get_type ())
#define MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MANAGER, Manager))
#define IS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MANAGER))
#define MANAGER_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_MANAGER, ManagerIface))

typedef struct _Manager Manager;
typedef struct _ManagerIface ManagerIface;

#define TYPE_MANAGER_PROXY (manager_proxy_get_type ())
typedef GDBusProxy ManagerProxy;
typedef GDBusProxyClass ManagerProxyClass;

#define TYPE_SERIAL (serial_get_type ())
#define SERIAL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERIAL, Serial))
#define IS_SERIAL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERIAL))
#define SERIAL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_SERIAL, SerialIface))

typedef struct _Serial Serial;
typedef struct _SerialIface SerialIface;

#define TYPE_SERIAL_PROXY (serial_proxy_get_type ())
typedef GDBusProxy SerialProxy;
typedef GDBusProxyClass SerialProxyClass;

#define TYPE_G_RAY (g_ray_get_type ())
#define G_RAY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_G_RAY, G_ray))
#define G_RAY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_G_RAY, G_rayClass))
#define IS_G_RAY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_G_RAY))
#define IS_G_RAY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_G_RAY))
#define G_RAY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_G_RAY, G_rayClass))

typedef struct _G_ray G_ray;
typedef struct _G_rayClass G_rayClass;
typedef struct _G_rayPrivate G_rayPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ParamSpecG_ray ParamSpecG_ray;

struct _AdapterIface {
	GTypeInterface parent_iface;
	void (*start_discovery) (Adapter* self, GError** error);
	void (*stop_discovery) (Adapter* self, GError** error);
};

struct _ManagerIface {
	GTypeInterface parent_iface;
	char* (*default_adapter) (Manager* self, GError** error);
};

struct _SerialIface {
	GTypeInterface parent_iface;
	gchar* (*Connect) (Serial* self, const gchar* param, GError** error);
	void (*Disconnect) (Serial* self, const gchar* device, GError** error);
};

struct _G_ray {
	GTypeInstance parent_instance;
	volatile int ref_count;
	G_rayPrivate * priv;
};

struct _G_rayClass {
	GTypeClass parent_class;
	void (*finalize) (G_ray *self);
};

struct _G_rayPrivate {
	Manager* m;
	Adapter* bluez;
	char* path;
	Serial* ser;
	gchar* _device;
	gint ndisc;
};

struct _ParamSpecG_ray {
	GParamSpec parent_instance;
};


static gpointer g_ray_parent_class = NULL;

GType adapter_proxy_get_type (void) G_GNUC_CONST;
guint adapter_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType adapter_get_type (void) G_GNUC_CONST;
void adapter_start_discovery (Adapter* self, GError** error);
void adapter_stop_discovery (Adapter* self, GError** error);
static void g_cclosure_user_marshal_VOID__STRING_BOXED (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__STRING_VARIANT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void adapter_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void _dbus_handle_adapter_device_found (Adapter* self, GVariant* parameters);
static void _dbus_handle_adapter_device_disappeared (Adapter* self, GVariant* parameters);
static void _dbus_handle_adapter_property_changed (Adapter* self, GVariant* parameters);
static void adapter_proxy_start_discovery (Adapter* self, GError** error);
static void adapter_proxy_stop_discovery (Adapter* self, GError** error);
static void adapter_proxy_adapter_interface_init (AdapterIface* iface);
static void _dbus_adapter_start_discovery (Adapter* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_adapter_stop_discovery (Adapter* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void adapter_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* adapter_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean adapter_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_adapter_device_found (GObject* _sender, const gchar* param0, GHashTable* param1, gpointer* _data);
static void _dbus_adapter_device_disappeared (GObject* _sender, const gchar* param0, gpointer* _data);
static void _dbus_adapter_property_changed (GObject* _sender, const gchar* param0, GVariant* param1, gpointer* _data);
static void _adapter_unregister_object (gpointer user_data);
GType manager_proxy_get_type (void) G_GNUC_CONST;
guint manager_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType manager_get_type (void) G_GNUC_CONST;
char* manager_default_adapter (Manager* self, GError** error);
static void manager_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static char* manager_proxy_default_adapter (Manager* self, GError** error);
static void manager_proxy_manager_interface_init (ManagerIface* iface);
static void _dbus_manager_default_adapter (Manager* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void manager_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* manager_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean manager_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _manager_unregister_object (gpointer user_data);
GType serial_proxy_get_type (void) G_GNUC_CONST;
guint serial_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType serial_get_type (void) G_GNUC_CONST;
gchar* serial_Connect (Serial* self, const gchar* param, GError** error);
void serial_Disconnect (Serial* self, const gchar* device, GError** error);
static void serial_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gchar* serial_proxy_Connect (Serial* self, const gchar* param, GError** error);
static void serial_proxy_Disconnect (Serial* self, const gchar* device, GError** error);
static void serial_proxy_serial_interface_init (SerialIface* iface);
static void _dbus_serial_Connect (Serial* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_serial_Disconnect (Serial* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void serial_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* serial_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean serial_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _serial_unregister_object (gpointer user_data);
gpointer g_ray_ref (gpointer instance);
void g_ray_unref (gpointer instance);
GParamSpec* param_spec_g_ray (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_g_ray (GValue* value, gpointer v_object);
void value_take_g_ray (GValue* value, gpointer v_object);
gpointer value_get_g_ray (const GValue* value);
GType g_ray_get_type (void) G_GNUC_CONST;
#define G_RAY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_G_RAY, G_rayPrivate))
enum  {
	G_RAY_DUMMY_PROPERTY
};
static void g_ray_on_device_found (G_ray* self, const gchar* address, GHashTable* hash);
static const gchar* _variant_get1 (GVariant* value);
void g_ray_set_device (G_ray* self, const gchar* value);
static void g_ray_on_device_disappeared (G_ray* self, const gchar* param0);
static void g_ray_on_property_changed (G_ray* self, const gchar* name, GVariant* val);
static gboolean _variant_get2 (GVariant* value);
gint g_ray_connect (G_ray* self);
static void _g_ray_on_device_found_adapter_device_found (Adapter* _sender, const gchar* param0, GHashTable* param1, gpointer self);
static void _g_ray_on_device_disappeared_adapter_device_disappeared (Adapter* _sender, const gchar* param0, gpointer self);
static void _g_ray_on_property_changed_adapter_property_changed (Adapter* _sender, const gchar* param0, GVariant* param1, gpointer self);
void g_ray_disconnect (G_ray* self);
const gchar* g_ray_get_device (G_ray* self);
G_ray* g_ray_new (void);
G_ray* g_ray_construct (GType object_type);
static void g_ray_finalize (G_ray* obj);

static const GDBusArgInfo * const _adapter_dbus_arg_info_start_discovery_in[] = {NULL};
static const GDBusArgInfo * const _adapter_dbus_arg_info_start_discovery_out[] = {NULL};
static const GDBusMethodInfo _adapter_dbus_method_info_start_discovery = {-1, "StartDiscovery", (GDBusArgInfo **) (&_adapter_dbus_arg_info_start_discovery_in), (GDBusArgInfo **) (&_adapter_dbus_arg_info_start_discovery_out)};
static const GDBusArgInfo * const _adapter_dbus_arg_info_stop_discovery_in[] = {NULL};
static const GDBusArgInfo * const _adapter_dbus_arg_info_stop_discovery_out[] = {NULL};
static const GDBusMethodInfo _adapter_dbus_method_info_stop_discovery = {-1, "StopDiscovery", (GDBusArgInfo **) (&_adapter_dbus_arg_info_stop_discovery_in), (GDBusArgInfo **) (&_adapter_dbus_arg_info_stop_discovery_out)};
static const GDBusMethodInfo * const _adapter_dbus_method_info[] = {&_adapter_dbus_method_info_start_discovery, &_adapter_dbus_method_info_stop_discovery, NULL};
static const GDBusArgInfo _adapter_dbus_arg_info_device_found_param0 = {-1, "param0", "s"};
static const GDBusArgInfo _adapter_dbus_arg_info_device_found_param1 = {-1, "param1", "a{sv}"};
static const GDBusArgInfo * const _adapter_dbus_arg_info_device_found[] = {&_adapter_dbus_arg_info_device_found_param0, &_adapter_dbus_arg_info_device_found_param1, NULL};
static const GDBusSignalInfo _adapter_dbus_signal_info_device_found = {-1, "DeviceFound", (GDBusArgInfo **) (&_adapter_dbus_arg_info_device_found)};
static const GDBusArgInfo _adapter_dbus_arg_info_device_disappeared_param0 = {-1, "param0", "s"};
static const GDBusArgInfo * const _adapter_dbus_arg_info_device_disappeared[] = {&_adapter_dbus_arg_info_device_disappeared_param0, NULL};
static const GDBusSignalInfo _adapter_dbus_signal_info_device_disappeared = {-1, "DeviceDisappeared", (GDBusArgInfo **) (&_adapter_dbus_arg_info_device_disappeared)};
static const GDBusArgInfo _adapter_dbus_arg_info_property_changed_param0 = {-1, "param0", "s"};
static const GDBusArgInfo _adapter_dbus_arg_info_property_changed_param1 = {-1, "param1", "v"};
static const GDBusArgInfo * const _adapter_dbus_arg_info_property_changed[] = {&_adapter_dbus_arg_info_property_changed_param0, &_adapter_dbus_arg_info_property_changed_param1, NULL};
static const GDBusSignalInfo _adapter_dbus_signal_info_property_changed = {-1, "PropertyChanged", (GDBusArgInfo **) (&_adapter_dbus_arg_info_property_changed)};
static const GDBusSignalInfo * const _adapter_dbus_signal_info[] = {&_adapter_dbus_signal_info_device_found, &_adapter_dbus_signal_info_device_disappeared, &_adapter_dbus_signal_info_property_changed, NULL};
static const GDBusPropertyInfo * const _adapter_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _adapter_dbus_interface_info = {-1, "org.bluez.Adapter", (GDBusMethodInfo **) (&_adapter_dbus_method_info), (GDBusSignalInfo **) (&_adapter_dbus_signal_info), (GDBusPropertyInfo **) (&_adapter_dbus_property_info)};
static const GDBusInterfaceVTable _adapter_dbus_interface_vtable = {adapter_dbus_interface_method_call, adapter_dbus_interface_get_property, adapter_dbus_interface_set_property};
static const GDBusArgInfo _manager_dbus_arg_info_default_adapter_result = {-1, "result", "o"};
static const GDBusArgInfo * const _manager_dbus_arg_info_default_adapter_in[] = {NULL};
static const GDBusArgInfo * const _manager_dbus_arg_info_default_adapter_out[] = {&_manager_dbus_arg_info_default_adapter_result, NULL};
static const GDBusMethodInfo _manager_dbus_method_info_default_adapter = {-1, "DefaultAdapter", (GDBusArgInfo **) (&_manager_dbus_arg_info_default_adapter_in), (GDBusArgInfo **) (&_manager_dbus_arg_info_default_adapter_out)};
static const GDBusMethodInfo * const _manager_dbus_method_info[] = {&_manager_dbus_method_info_default_adapter, NULL};
static const GDBusSignalInfo * const _manager_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _manager_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _manager_dbus_interface_info = {-1, "org.bluez.Manager", (GDBusMethodInfo **) (&_manager_dbus_method_info), (GDBusSignalInfo **) (&_manager_dbus_signal_info), (GDBusPropertyInfo **) (&_manager_dbus_property_info)};
static const GDBusInterfaceVTable _manager_dbus_interface_vtable = {manager_dbus_interface_method_call, manager_dbus_interface_get_property, manager_dbus_interface_set_property};
static const GDBusArgInfo _serial_dbus_arg_info_Connect_param = {-1, "param", "s"};
static const GDBusArgInfo _serial_dbus_arg_info_Connect_result = {-1, "result", "s"};
static const GDBusArgInfo * const _serial_dbus_arg_info_Connect_in[] = {&_serial_dbus_arg_info_Connect_param, NULL};
static const GDBusArgInfo * const _serial_dbus_arg_info_Connect_out[] = {&_serial_dbus_arg_info_Connect_result, NULL};
static const GDBusMethodInfo _serial_dbus_method_info_Connect = {-1, "Connect", (GDBusArgInfo **) (&_serial_dbus_arg_info_Connect_in), (GDBusArgInfo **) (&_serial_dbus_arg_info_Connect_out)};
static const GDBusArgInfo _serial_dbus_arg_info_Disconnect_device = {-1, "device", "s"};
static const GDBusArgInfo * const _serial_dbus_arg_info_Disconnect_in[] = {&_serial_dbus_arg_info_Disconnect_device, NULL};
static const GDBusArgInfo * const _serial_dbus_arg_info_Disconnect_out[] = {NULL};
static const GDBusMethodInfo _serial_dbus_method_info_Disconnect = {-1, "Disconnect", (GDBusArgInfo **) (&_serial_dbus_arg_info_Disconnect_in), (GDBusArgInfo **) (&_serial_dbus_arg_info_Disconnect_out)};
static const GDBusMethodInfo * const _serial_dbus_method_info[] = {&_serial_dbus_method_info_Connect, &_serial_dbus_method_info_Disconnect, NULL};
static const GDBusSignalInfo * const _serial_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _serial_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _serial_dbus_interface_info = {-1, "org.bluez.Serial", (GDBusMethodInfo **) (&_serial_dbus_method_info), (GDBusSignalInfo **) (&_serial_dbus_signal_info), (GDBusPropertyInfo **) (&_serial_dbus_property_info)};
static const GDBusInterfaceVTable _serial_dbus_interface_vtable = {serial_dbus_interface_method_call, serial_dbus_interface_get_property, serial_dbus_interface_set_property};

void adapter_start_discovery (Adapter* self, GError** error) {
	g_return_if_fail (self != NULL);
	ADAPTER_GET_INTERFACE (self)->start_discovery (self, error);
}


void adapter_stop_discovery (Adapter* self, GError** error) {
	g_return_if_fail (self != NULL);
	ADAPTER_GET_INTERFACE (self)->stop_discovery (self, error);
}


static void g_cclosure_user_marshal_VOID__STRING_BOXED (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__STRING_BOXED) (gpointer data1, const char* arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_BOXED callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_BOXED) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_boxed (param_values + 2), data2);
}


static void g_cclosure_user_marshal_VOID__STRING_VARIANT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__STRING_VARIANT) (gpointer data1, const char* arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_VARIANT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_VARIANT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_variant (param_values + 2), data2);
}


static void adapter_base_init (AdapterIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_signal_new ("device_found", TYPE_ADAPTER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_BOXED, G_TYPE_NONE, 2, G_TYPE_STRING, G_TYPE_HASH_TABLE);
		g_signal_new ("device_disappeared", TYPE_ADAPTER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
		g_signal_new ("property_changed", TYPE_ADAPTER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_VARIANT, G_TYPE_NONE, 2, G_TYPE_STRING, G_TYPE_VARIANT);
	}
}


GType adapter_get_type (void) {
	static volatile gsize adapter_type_id__volatile = 0;
	if (g_once_init_enter (&adapter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdapterIface), (GBaseInitFunc) adapter_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType adapter_type_id;
		adapter_type_id = g_type_register_static (G_TYPE_INTERFACE, "Adapter", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (adapter_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (adapter_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) adapter_proxy_get_type);
		g_type_set_qdata (adapter_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.bluez.Adapter");
		g_type_set_qdata (adapter_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) adapter_register_object);
		g_once_init_leave (&adapter_type_id__volatile, adapter_type_id);
	}
	return adapter_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (AdapterProxy, adapter_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_ADAPTER, adapter_proxy_adapter_interface_init) )
static void adapter_proxy_class_init (AdapterProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = adapter_proxy_g_signal;
}


static void _dbus_handle_adapter_device_found (Adapter* self, GVariant* parameters) {
	GVariantIter _arguments_iter;
	gchar* param0 = NULL;
	GVariant* _tmp0_;
	GHashTable* param1 = NULL;
	GVariant* _tmp1_;
	GHashTable* _tmp2_;
	GVariantIter _tmp3_;
	GVariant* _tmp4_;
	GVariant* _tmp5_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	param0 = g_variant_dup_string (_tmp0_, NULL);
	g_variant_unref (_tmp0_);
	_tmp1_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp2_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp3_, _tmp1_);
	while (g_variant_iter_loop (&_tmp3_, "{?*}", &_tmp4_, &_tmp5_)) {
		g_hash_table_insert (_tmp2_, g_variant_dup_string (_tmp4_, NULL), g_variant_get_variant (_tmp5_));
	}
	param1 = _tmp2_;
	g_variant_unref (_tmp1_);
	g_signal_emit_by_name (self, "device-found", param0, param1);
	_g_free0 (param0);
	_g_hash_table_unref0 (param1);
}


static void _dbus_handle_adapter_device_disappeared (Adapter* self, GVariant* parameters) {
	GVariantIter _arguments_iter;
	gchar* param0 = NULL;
	GVariant* _tmp6_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp6_ = g_variant_iter_next_value (&_arguments_iter);
	param0 = g_variant_dup_string (_tmp6_, NULL);
	g_variant_unref (_tmp6_);
	g_signal_emit_by_name (self, "device-disappeared", param0);
	_g_free0 (param0);
}


static void _dbus_handle_adapter_property_changed (Adapter* self, GVariant* parameters) {
	GVariantIter _arguments_iter;
	gchar* param0 = NULL;
	GVariant* _tmp7_;
	GVariant* param1 = NULL;
	GVariant* _tmp8_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp7_ = g_variant_iter_next_value (&_arguments_iter);
	param0 = g_variant_dup_string (_tmp7_, NULL);
	g_variant_unref (_tmp7_);
	_tmp8_ = g_variant_iter_next_value (&_arguments_iter);
	param1 = g_variant_get_variant (_tmp8_);
	g_variant_unref (_tmp8_);
	g_signal_emit_by_name (self, "property-changed", param0, param1);
	_g_free0 (param0);
	_g_variant_unref0 (param1);
}


static void adapter_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
	if (strcmp (signal_name, "DeviceFound") == 0) {
		_dbus_handle_adapter_device_found ((Adapter*) proxy, parameters);
	} else if (strcmp (signal_name, "DeviceDisappeared") == 0) {
		_dbus_handle_adapter_device_disappeared ((Adapter*) proxy, parameters);
	} else if (strcmp (signal_name, "PropertyChanged") == 0) {
		_dbus_handle_adapter_property_changed ((Adapter*) proxy, parameters);
	}
}


static void adapter_proxy_init (AdapterProxy* self) {
}


static void adapter_proxy_start_discovery (Adapter* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Adapter", "StartDiscovery");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void adapter_proxy_stop_discovery (Adapter* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Adapter", "StopDiscovery");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void adapter_proxy_adapter_interface_init (AdapterIface* iface) {
	iface->start_discovery = adapter_proxy_start_discovery;
	iface->stop_discovery = adapter_proxy_stop_discovery;
}


static void _dbus_adapter_start_discovery (Adapter* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	adapter_start_discovery (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_adapter_stop_discovery (Adapter* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	adapter_stop_discovery (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void adapter_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "StartDiscovery") == 0) {
		_dbus_adapter_start_discovery (object, parameters, invocation);
	} else if (strcmp (method_name, "StopDiscovery") == 0) {
		_dbus_adapter_stop_discovery (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* adapter_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean adapter_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_adapter_device_found (GObject* _sender, const gchar* param0, GHashTable* param1, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GVariantBuilder _tmp9_;
	GHashTableIter _tmp10_;
	gpointer _tmp11_;
	gpointer _tmp12_;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (param0));
	g_hash_table_iter_init (&_tmp10_, param1);
	g_variant_builder_init (&_tmp9_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp10_, &_tmp11_, &_tmp12_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp11_;
		_value = (GVariant*) _tmp12_;
		g_variant_builder_add (&_tmp9_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp9_));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter", "DeviceFound", _arguments, NULL);
}


static void _dbus_adapter_device_disappeared (GObject* _sender, const gchar* param0, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (param0));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter", "DeviceDisappeared", _arguments, NULL);
}


static void _dbus_adapter_property_changed (GObject* _sender, const gchar* param0, GVariant* param1, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (param0));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_variant (param1));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.bluez.Adapter", "PropertyChanged", _arguments, NULL);
}


guint adapter_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_adapter_dbus_interface_info), &_adapter_dbus_interface_vtable, data, _adapter_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "device-found", (GCallback) _dbus_adapter_device_found, data);
	g_signal_connect (object, "device-disappeared", (GCallback) _dbus_adapter_device_disappeared, data);
	g_signal_connect (object, "property-changed", (GCallback) _dbus_adapter_property_changed, data);
	return result;
}


static void _adapter_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_adapter_device_found, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_adapter_device_disappeared, data);
	g_signal_handlers_disconnect_by_func (data[0], _dbus_adapter_property_changed, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


char* manager_default_adapter (Manager* self, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return MANAGER_GET_INTERFACE (self)->default_adapter (self, error);
}


static void manager_base_init (ManagerIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType manager_get_type (void) {
	static volatile gsize manager_type_id__volatile = 0;
	if (g_once_init_enter (&manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ManagerIface), (GBaseInitFunc) manager_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType manager_type_id;
		manager_type_id = g_type_register_static (G_TYPE_INTERFACE, "Manager", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (manager_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (manager_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) manager_proxy_get_type);
		g_type_set_qdata (manager_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.bluez.Manager");
		g_type_set_qdata (manager_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) manager_register_object);
		g_once_init_leave (&manager_type_id__volatile, manager_type_id);
	}
	return manager_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (ManagerProxy, manager_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_MANAGER, manager_proxy_manager_interface_init) )
static void manager_proxy_class_init (ManagerProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = manager_proxy_g_signal;
}


static void manager_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void manager_proxy_init (ManagerProxy* self) {
}


static char* manager_proxy_default_adapter (Manager* self, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	char* _result;
	GVariant* _tmp13_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Manager", "DefaultAdapter");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp13_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_dup_string (_tmp13_, NULL);
	g_variant_unref (_tmp13_);
	g_object_unref (_reply_message);
	return _result;
}


static void manager_proxy_manager_interface_init (ManagerIface* iface) {
	iface->default_adapter = manager_proxy_default_adapter;
}


static void _dbus_manager_default_adapter (Manager* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	char* result;
	g_variant_iter_init (&_arguments_iter, parameters);
	result = manager_default_adapter (self, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_object_path (result));
	_g_free0 (result);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void manager_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "DefaultAdapter") == 0) {
		_dbus_manager_default_adapter (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* manager_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean manager_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint manager_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_manager_dbus_interface_info), &_manager_dbus_interface_vtable, data, _manager_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _manager_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


gchar* serial_Connect (Serial* self, const gchar* param, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return SERIAL_GET_INTERFACE (self)->Connect (self, param, error);
}


void serial_Disconnect (Serial* self, const gchar* device, GError** error) {
	g_return_if_fail (self != NULL);
	SERIAL_GET_INTERFACE (self)->Disconnect (self, device, error);
}


static void serial_base_init (SerialIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType serial_get_type (void) {
	static volatile gsize serial_type_id__volatile = 0;
	if (g_once_init_enter (&serial_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SerialIface), (GBaseInitFunc) serial_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType serial_type_id;
		serial_type_id = g_type_register_static (G_TYPE_INTERFACE, "Serial", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (serial_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (serial_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) serial_proxy_get_type);
		g_type_set_qdata (serial_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.bluez.Serial");
		g_type_set_qdata (serial_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) serial_register_object);
		g_once_init_leave (&serial_type_id__volatile, serial_type_id);
	}
	return serial_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (SerialProxy, serial_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_SERIAL, serial_proxy_serial_interface_init) )
static void serial_proxy_class_init (SerialProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = serial_proxy_g_signal;
}


static void serial_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void serial_proxy_init (SerialProxy* self) {
}


static gchar* serial_proxy_Connect (Serial* self, const gchar* param, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar* _result;
	GVariant* _tmp14_;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Serial", "Connect");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (param));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp14_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_dup_string (_tmp14_, NULL);
	g_variant_unref (_tmp14_);
	g_object_unref (_reply_message);
	return _result;
}


static void serial_proxy_Disconnect (Serial* self, const gchar* device, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.bluez.Serial", "Disconnect");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (device));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void serial_proxy_serial_interface_init (SerialIface* iface) {
	iface->Connect = serial_proxy_Connect;
	iface->Disconnect = serial_proxy_Disconnect;
}


static void _dbus_serial_Connect (Serial* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* param = NULL;
	GVariant* _tmp15_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar* result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp15_ = g_variant_iter_next_value (&_arguments_iter);
	param = g_variant_dup_string (_tmp15_, NULL);
	g_variant_unref (_tmp15_);
	result = serial_Connect (self, param, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_g_free0 (result);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (param);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_serial_Disconnect (Serial* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* device = NULL;
	GVariant* _tmp16_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp16_ = g_variant_iter_next_value (&_arguments_iter);
	device = g_variant_dup_string (_tmp16_, NULL);
	g_variant_unref (_tmp16_);
	serial_Disconnect (self, device, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (device);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void serial_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Connect") == 0) {
		_dbus_serial_Connect (object, parameters, invocation);
	} else if (strcmp (method_name, "Disconnect") == 0) {
		_dbus_serial_Disconnect (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* serial_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean serial_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint serial_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_serial_dbus_interface_info), &_serial_dbus_interface_vtable, data, _serial_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _serial_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


static const gchar* _variant_get1 (GVariant* value) {
	return g_variant_dup_string (value, NULL);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally1;
	__catch1_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void g_ray_on_device_found (G_ray* self, const gchar* address, GHashTable* hash) {
	GHashTable* _tmp0_;
	gconstpointer _tmp1_ = NULL;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* name;
	const gchar* _tmp4_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (address != NULL);
	g_return_if_fail (hash != NULL);
	_tmp0_ = hash;
	_tmp1_ = g_hash_table_lookup (_tmp0_, "Name");
	_tmp2_ = _variant_get1 ((GVariant*) _tmp1_);
	_tmp3_ = g_strdup (_tmp2_);
	name = _tmp3_;
	_tmp4_ = name;
	if (g_strcmp0 (_tmp4_, "G-Rays2") == 0) {
		{
			Adapter* _tmp5_;
			const char* _tmp6_;
			const gchar* _tmp7_;
			gchar* _tmp8_ = NULL;
			gchar* _tmp9_;
			gchar* _tmp10_ = NULL;
			gchar* _tmp11_;
			gchar* dev;
			const gchar* _tmp12_;
			Serial* _tmp13_ = NULL;
			Serial* _tmp14_;
			Serial* _tmp15_;
			gchar* _tmp16_ = NULL;
			gchar* _tmp17_;
			gchar* _tmp18_;
			_tmp5_ = self->priv->bluez;
			adapter_stop_discovery (_tmp5_, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch0_g_error;
			}
			_tmp6_ = self->priv->path;
			_tmp7_ = address;
			_tmp8_ = g_strdup_printf ("%s/dev_%s", (const gchar*) _tmp6_, _tmp7_);
			_tmp9_ = _tmp8_;
			_tmp10_ = string_replace (_tmp9_, ":", "_");
			_tmp11_ = _tmp10_;
			_g_free0 (_tmp9_);
			dev = _tmp11_;
			_tmp12_ = dev;
			_tmp13_ = g_initable_new (TYPE_SERIAL_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.bluez", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", _tmp12_, "g-interface-name", "org.bluez.Serial", NULL);
			_tmp14_ = (Serial*) _tmp13_;
			if (_inner_error_ != NULL) {
				_g_free0 (dev);
				goto __catch0_g_error;
			}
			_g_object_unref0 (self->priv->ser);
			self->priv->ser = _tmp14_;
			_tmp15_ = self->priv->ser;
			_tmp16_ = serial_Connect (_tmp15_, "spp", &_inner_error_);
			_tmp17_ = _tmp16_;
			if (_inner_error_ != NULL) {
				_g_free0 (dev);
				goto __catch0_g_error;
			}
			_tmp18_ = _tmp17_;
			g_ray_set_device (self, _tmp18_);
			_g_free0 (_tmp18_);
			_g_free0 (dev);
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError* e = NULL;
			FILE* _tmp19_;
			GError* _tmp20_;
			const gchar* _tmp21_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp19_ = stderr;
			_tmp20_ = e;
			_tmp21_ = _tmp20_->message;
			fprintf (_tmp19_, "%s\n", _tmp21_);
			_g_error_free0 (e);
		}
		__finally0:
		if (_inner_error_ != NULL) {
			_g_free0 (name);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		gtk_main_quit ();
	}
	_g_free0 (name);
}


static void g_ray_on_device_disappeared (G_ray* self, const gchar* param0) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (param0 != NULL);
	_tmp0_ = stdout;
	_tmp1_ = param0;
	fprintf (_tmp0_, "Remote device gone (%s)\n", _tmp1_);
}


static gboolean _variant_get2 (GVariant* value) {
	return g_variant_get_boolean (value);
}


static void g_ray_on_property_changed (G_ray* self, const gchar* name, GVariant* val) {
	const gchar* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	g_return_if_fail (val != NULL);
	_tmp0_ = name;
	if (g_strcmp0 (_tmp0_, "Discovering") == 0) {
		GVariant* _tmp1_;
		gboolean _tmp2_;
		_tmp1_ = val;
		_tmp2_ = _variant_get2 (_tmp1_);
		if (_tmp2_ == TRUE) {
			gint _tmp3_;
			gint _tmp4_;
			_tmp3_ = self->priv->ndisc;
			self->priv->ndisc = _tmp3_ + 1;
			_tmp4_ = self->priv->ndisc;
			if (_tmp4_ == 3) {
				{
					Adapter* _tmp5_;
					_tmp5_ = self->priv->bluez;
					adapter_stop_discovery (_tmp5_, &_inner_error_);
					if (_inner_error_ != NULL) {
						goto __catch2_g_error;
					}
				}
				goto __finally2;
				__catch2_g_error:
				{
					GError* e = NULL;
					FILE* _tmp6_;
					GError* _tmp7_;
					const gchar* _tmp8_;
					e = _inner_error_;
					_inner_error_ = NULL;
					_tmp6_ = stderr;
					_tmp7_ = e;
					_tmp8_ = _tmp7_->message;
					fprintf (_tmp6_, "%s\n", _tmp8_);
					_g_error_free0 (e);
				}
				__finally2:
				if (_inner_error_ != NULL) {
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				gtk_main_quit ();
			}
		}
	}
}


static void _g_ray_on_device_found_adapter_device_found (Adapter* _sender, const gchar* param0, GHashTable* param1, gpointer self) {
	g_ray_on_device_found (self, param0, param1);
}


static void _g_ray_on_device_disappeared_adapter_device_disappeared (Adapter* _sender, const gchar* param0, gpointer self) {
	g_ray_on_device_disappeared (self, param0);
}


static void _g_ray_on_property_changed_adapter_property_changed (Adapter* _sender, const gchar* param0, GVariant* param1, gpointer self) {
	g_ray_on_property_changed (self, param0, param1);
}


gint g_ray_connect (G_ray* self) {
	gint result = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	{
		Manager* _tmp0_ = NULL;
		Manager* _tmp1_;
		Manager* _tmp2_;
		char* _tmp3_ = NULL;
		char* _tmp4_;
		const char* _tmp5_;
		Adapter* _tmp6_ = NULL;
		Adapter* _tmp7_;
		Adapter* _tmp8_;
		Adapter* _tmp9_;
		Adapter* _tmp10_;
		Adapter* _tmp11_;
		_tmp0_ = g_initable_new (TYPE_MANAGER_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.bluez", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/", "g-interface-name", "org.bluez.Manager", NULL);
		_tmp1_ = (Manager*) _tmp0_;
		if (_inner_error_ != NULL) {
			goto __catch3_g_error;
		}
		_g_object_unref0 (self->priv->m);
		self->priv->m = _tmp1_;
		_tmp2_ = self->priv->m;
		_tmp3_ = manager_default_adapter (_tmp2_, &_inner_error_);
		_tmp4_ = _tmp3_;
		if (_inner_error_ != NULL) {
			goto __catch3_g_error;
		}
		_g_free0 (self->priv->path);
		self->priv->path = _tmp4_;
		_tmp5_ = self->priv->path;
		_tmp6_ = g_initable_new (TYPE_ADAPTER_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "org.bluez", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", (const gchar*) _tmp5_, "g-interface-name", "org.bluez.Adapter", NULL);
		_tmp7_ = (Adapter*) _tmp6_;
		if (_inner_error_ != NULL) {
			goto __catch3_g_error;
		}
		_g_object_unref0 (self->priv->bluez);
		self->priv->bluez = _tmp7_;
		_tmp8_ = self->priv->bluez;
		g_signal_connect (_tmp8_, "device-found", (GCallback) _g_ray_on_device_found_adapter_device_found, self);
		_tmp9_ = self->priv->bluez;
		g_signal_connect (_tmp9_, "device-disappeared", (GCallback) _g_ray_on_device_disappeared_adapter_device_disappeared, self);
		_tmp10_ = self->priv->bluez;
		g_signal_connect (_tmp10_, "property-changed", (GCallback) _g_ray_on_property_changed_adapter_property_changed, self);
		self->priv->ndisc = 0;
		_tmp11_ = self->priv->bluez;
		adapter_start_discovery (_tmp11_, &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch3_g_error;
		}
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		FILE* _tmp12_;
		GError* _tmp13_;
		const gchar* _tmp14_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp12_ = stderr;
		_tmp13_ = e;
		_tmp14_ = _tmp13_->message;
		fprintf (_tmp12_, "%s\n", _tmp14_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally3:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}


void g_ray_disconnect (G_ray* self) {
	const gchar* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_device;
	if (_tmp0_ != NULL) {
		{
			Serial* _tmp1_;
			const gchar* _tmp2_;
			_tmp1_ = self->priv->ser;
			_tmp2_ = self->priv->_device;
			serial_Disconnect (_tmp1_, _tmp2_, &_inner_error_);
			if (_inner_error_ != NULL) {
				goto __catch4_g_error;
			}
		}
		goto __finally4;
		__catch4_g_error:
		{
			GError* e = NULL;
			FILE* _tmp3_;
			GError* _tmp4_;
			const gchar* _tmp5_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp3_ = stderr;
			_tmp4_ = e;
			_tmp5_ = _tmp4_->message;
			fprintf (_tmp3_, "%s\n", _tmp5_);
			_g_error_free0 (e);
		}
		__finally4:
		if (_inner_error_ != NULL) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		g_ray_set_device (self, NULL);
	}
}


G_ray* g_ray_construct (GType object_type) {
	G_ray* self = NULL;
	self = (G_ray*) g_type_create_instance (object_type);
	return self;
}


G_ray* g_ray_new (void) {
	return g_ray_construct (TYPE_G_RAY);
}


const gchar* g_ray_get_device (G_ray* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_device;
	result = _tmp0_;
	return result;
}


void g_ray_set_device (G_ray* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_device);
	self->priv->_device = _tmp1_;
}


static void value_g_ray_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_g_ray_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		g_ray_unref (value->data[0].v_pointer);
	}
}


static void value_g_ray_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = g_ray_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_g_ray_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_g_ray_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		G_ray* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = g_ray_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_g_ray_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	G_ray** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = g_ray_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_g_ray (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecG_ray* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_G_RAY), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_g_ray (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_G_RAY), NULL);
	return value->data[0].v_pointer;
}


void value_set_g_ray (GValue* value, gpointer v_object) {
	G_ray* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_G_RAY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_G_RAY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		g_ray_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		g_ray_unref (old);
	}
}


void value_take_g_ray (GValue* value, gpointer v_object) {
	G_ray* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_G_RAY));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_G_RAY));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		g_ray_unref (old);
	}
}


static void g_ray_class_init (G_rayClass * klass) {
	g_ray_parent_class = g_type_class_peek_parent (klass);
	G_RAY_CLASS (klass)->finalize = g_ray_finalize;
	g_type_class_add_private (klass, sizeof (G_rayPrivate));
}


static void g_ray_instance_init (G_ray * self) {
	self->priv = G_RAY_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void g_ray_finalize (G_ray* obj) {
	G_ray * self;
	self = G_RAY (obj);
	_g_object_unref0 (self->priv->m);
	_g_object_unref0 (self->priv->bluez);
	_g_free0 (self->priv->path);
	_g_object_unref0 (self->priv->ser);
	_g_free0 (self->priv->_device);
}


GType g_ray_get_type (void) {
	static volatile gsize g_ray_type_id__volatile = 0;
	if (g_once_init_enter (&g_ray_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_g_ray_init, value_g_ray_free_value, value_g_ray_copy_value, value_g_ray_peek_pointer, "p", value_g_ray_collect_value, "p", value_g_ray_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (G_rayClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) g_ray_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (G_ray), 0, (GInstanceInitFunc) g_ray_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType g_ray_type_id;
		g_ray_type_id = g_type_register_fundamental (g_type_fundamental_next (), "G_ray", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&g_ray_type_id__volatile, g_ray_type_id);
	}
	return g_ray_type_id__volatile;
}


gpointer g_ray_ref (gpointer instance) {
	G_ray* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void g_ray_unref (gpointer instance) {
	G_ray* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		G_RAY_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



