CC=gcc

CFLAGS=-DMAKE_MAIN=1 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng15 -I/usr/include/gudev-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -O2 -D_GNU_SOURCE=1 -g

LIBS=-Wl,--export-dynamic -pthread  -lgtk-3 -lgdk-3 -latk-1.0 -lgio-2.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lpango-1.0 -lgmodule-2.0 -lgudev-1.0 -ldbus-glib-1 -ldbus-1 -lpthread -lrt -lgobject-2.0 -lglib-2.0 -lm -lcairo -pthread

LDFLAGS=-g

all: bmain

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $<

bmain : bmain.o grays_marshal.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)


bmtest : bmtest.o grays_marshal.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)


gstest: gstest.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

bmain_spawn: bmain_spawn.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

bmain_sock: bmain_sock.o
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS) -lbluetooth


clean: 
	rm -f bmain bmtest bmain.o bmtest.o bmain_sock bmain_sock.o bmain_spawn.o bmain_spawn

